#if !defined(__PINPAD_INTERNAL_CMD_COST_H_)
#define __PINPAD_INTERNAL_CMD_COST_H_

//Command index
#define	CMD_OPEN			1
#define	CMD_CLOSE			2
#define	CMD_WRITE			10
#define	CMD_READ			11
#define	CMD_TRANSMIT		12
#define	CMD_POWERON			13
#define	CMD_POWEROFF		14
#define	CMD_EXSIT			15

#define	CMD_STOP_TIMEOUT	40	
#define	CMD_GETPIN			50
#define	CMD_GETPINEX		51

#define	CMD_GETPINEXAUTO	52

#define	CMD_CANCEL			53
#define	CMD_DISPLAYMSG		54
#define	CMD_DISPLAY_REC		55
#define	CMD_VOICEMSG		56



#define	CMD_GETACCEX		60
#define	CMD_GETPINACCEX		61
#define	CMD_GETPINACCEXAUTO	62
#define	CMD_ACCCANCEL		63

#define	CMD_SINHYUP_GETPIN_RE			70
#define	CMD_SINHYUP_GETPINEX_RE			71
#define	CMD_SINHYUP_GETUSERID			72
#define	CMD_SINHYUP_GETUSERIDEX			73
#define	CMD_SINHYUP_GETUSERID_RE		74
#define	CMD_SINHYUP_GETUSERIDEX_RE		75
#define	CMD_SINHYUP_DISPLAY_ERROR_MSG	76
#define	CMD_SINHYUP_VOICE_MSG			77
#define	CMD_SINHYUP_GETACC				78
#define	CMD_SINHYUP_GETACCEX			79


#define CMD_RAW_READ		100
#define CMD_RAW_WRITE		101
//
#endif//__PINPAD_INTERNAL_CMD_COST_H_