# li_lpu237_jni.ld
{
    global:
		Java_kr_co_elpusk_javapos_msr_Lpu237MSRService_initIDs;
		Java_kr_co_elpusk_javapos_msr_Lpu237MSRService_lpu237_1cancel_1wait;
		Java_kr_co_elpusk_javapos_msr_Lpu237MSRService_lpu237_1wait_1read;
		Java_kr_co_elpusk_javapos_msr_Lpu237MSRService_lpu237_1enable_1read;
		Java_kr_co_elpusk_javapos_msr_Lpu237MSRService_lpu237_1open;
		Java_kr_co_elpusk_javapos_msr_Lpu237MSRService_lpu237_1close;
		Java_kr_co_elpusk_javapos_msr_Lpu237MSRService_lpu237_1ini;
		Java_kr_co_elpusk_javapos_msr_Lpu237MSRService_lpu237_1end;
		_so_init;
		_so_fini;
    local:
        *;
};
