/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kr_co_elpusk_javapos_msr_Lpu237MSRService */

#ifndef _Included_kr_co_elpusk_javapos_msr_Lpu237MSRService
#define _Included_kr_co_elpusk_javapos_msr_Lpu237MSRService
#ifdef __cplusplus
extern "C" {
#endif
#undef kr_co_elpusk_javapos_msr_Lpu237MSRService_serialVersionUID
#define kr_co_elpusk_javapos_msr_Lpu237MSRService_serialVersionUID 2017800100i64
#undef kr_co_elpusk_javapos_msr_Lpu237MSRService_DEVICE_VERSION
#define kr_co_elpusk_javapos_msr_Lpu237MSRService_DEVICE_VERSION 1011000L
#undef kr_co_elpusk_javapos_msr_Lpu237MSRService_serialVersionUID
#define kr_co_elpusk_javapos_msr_Lpu237MSRService_serialVersionUID 2017082300i64
#undef kr_co_elpusk_javapos_msr_Lpu237MSRService_iso_buffer_size
#define kr_co_elpusk_javapos_msr_Lpu237MSRService_iso_buffer_size 120L
#undef kr_co_elpusk_javapos_msr_Lpu237MSRService_iso1_stx
#define kr_co_elpusk_javapos_msr_Lpu237MSRService_iso1_stx 37L
#undef kr_co_elpusk_javapos_msr_Lpu237MSRService_iso1_etx
#define kr_co_elpusk_javapos_msr_Lpu237MSRService_iso1_etx 63L
#undef kr_co_elpusk_javapos_msr_Lpu237MSRService_iso2_3_stx
#define kr_co_elpusk_javapos_msr_Lpu237MSRService_iso2_3_stx 59L
#undef kr_co_elpusk_javapos_msr_Lpu237MSRService_iso2_3_etx
#define kr_co_elpusk_javapos_msr_Lpu237MSRService_iso2_3_etx 63L
#undef kr_co_elpusk_javapos_msr_Lpu237MSRService_join_wait_time_mm
#define kr_co_elpusk_javapos_msr_Lpu237MSRService_join_wait_time_mm 3000i64
/*
 * Class:     kr_co_elpusk_javapos_msr_Lpu237MSRService
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_kr_co_elpusk_javapos_msr_Lpu237MSRService_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     kr_co_elpusk_javapos_msr_Lpu237MSRService
 * Method:    lpu237_cancel_wait
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_kr_co_elpusk_javapos_msr_Lpu237MSRService_lpu237_1cancel_1wait
  (JNIEnv *, jobject);

/*
 * Class:     kr_co_elpusk_javapos_msr_Lpu237MSRService
 * Method:    lpu237_wait_read
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_kr_co_elpusk_javapos_msr_Lpu237MSRService_lpu237_1wait_1read
  (JNIEnv *, jobject);

/*
 * Class:     kr_co_elpusk_javapos_msr_Lpu237MSRService
 * Method:    lpu237_enable_read
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_kr_co_elpusk_javapos_msr_Lpu237MSRService_lpu237_1enable_1read
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     kr_co_elpusk_javapos_msr_Lpu237MSRService
 * Method:    lpu237_open
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_kr_co_elpusk_javapos_msr_Lpu237MSRService_lpu237_1open
  (JNIEnv *, jobject);

/*
 * Class:     kr_co_elpusk_javapos_msr_Lpu237MSRService
 * Method:    lpu237_close
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_kr_co_elpusk_javapos_msr_Lpu237MSRService_lpu237_1close
  (JNIEnv *, jobject);

/*
 * Class:     kr_co_elpusk_javapos_msr_Lpu237MSRService
 * Method:    lpu237_ini
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_kr_co_elpusk_javapos_msr_Lpu237MSRService_lpu237_1ini
  (JNIEnv *, jobject);

/*
 * Class:     kr_co_elpusk_javapos_msr_Lpu237MSRService
 * Method:    lpu237_end
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_kr_co_elpusk_javapos_msr_Lpu237MSRService_lpu237_1end
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
